version: 2.1
orbs:
  welcome: circleci/welcome-orb@0.4.1


commands:
  my-command:
    parameters:
      msg:
        description: message to be print
        type: string
        default: "hello"
    steps:
        - checkout 
        - run: echo << parameters.msg >>
  
jobs:
  build-first:
    machine: true
    steps:
      - my-command
          msg: "msg from first build"
  build-second:
    machine: true
    steps:
      - my-command
          msg: "msg from second build"
    
workflows:
  my-workflow:
    jobs:
      - build-first
      - build-second:
          requires:
            - build-first
