version: 2.1
orbs:
  welcome: circleci/welcome-orb@0.4.1

jobs:
  build-first:
    - welcome/run
  build-second:
    - welcome/run
    
workflows:
  my-workflow:
    jobs:
      - build-first
      - build-second
