version: 2.1
orbs:
  welcome: circleci/welcome-orb@0.4.1

jobs:
    buildfirst:
        - welcome/run
    buildsecond:
        - welcome/run
    
workflows:
  my-workflow:
    jobs:
      - buildfirst
      - buildsecond
