version: 2.1
orbs:
  welcome: circleci/welcome-orb@0.4.1

jobs:
  build-first:
    machine: true
      - run: echo 'first build'
  build-second:
    machine: true
      - run: echo 'second build'
    
workflows:
  my-workflow:
    jobs:
      - build-first
      - build-second
