version: 2.1
orbs:
  welcome: circleci/welcome-orb@0.4.1


commands:
  my-command:
    steps:
        - checkout 
        - run: echo "hello world"
  
jobs:
  build-first:
    machine: true
    steps:
      - my-command
  build-second:
    machine: true
    steps:
      - my-command
    
workflows:
  my-workflow:
    jobs:
      - build-first
      - build-second:
          requires:
            - build-first
