version: 2.1
orbs:
  welcome: circleci/welcome-orb@0.4.1

jobs:
    build1:
        - welcome/run
    build2:
      - welcome/run
    
workflows:
  my-workflow:
    jobs:
      - build1
      - build2
