version: 2.1
orbs:
  welcome: circleci/welcome-orb@0.4.1

jobs:
  build-first:
    machine: true
    steps:
      - checkout 
      - run: echo "hello world"
  build-second:
    machine: true
    steps:
      - checkout 
      - run: echo "hello world"
    
workflows:
  my-workflow:
    jobs:
      - build-first
      - build-second
